 <div className="bg-white rounded-2xl shadow-md p-6">

                <div className="flex justify-between items-center mb-5">

                  <div>

                    <h2 className="text-2xl font-bold">

                      🏆 Best Proposal

                    </h2>

                    <p className="text-gray-500">

                      Generated by

                      <span className="font-semibold text-blue-600 ml-2">

                        {result.data.best_model}

                      </span>

                    </p>

                  </div>

                  <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">

                    {result.data.best_score}/100

                  </span>

                </div>

                <div className="whitespace-pre-wrap leading-8 text-gray-700 border rounded-xl p-5 bg-gray-50">

                  {result.data.best_proposal}

                </div>

              </div>