import { useState } from "react";
import api from "../services/api";
import { ChevronDown, ChevronUp, Copy, Check } from "lucide-react";

function ProposalCompare() {
  const [formData, setFormData] = useState({
    job_post: "",
    tone: "professional",
    skill: "",
  });
    const [showAll, setShowAll] = useState(false);
    const [copiedIndex, setCopiedIndex] = useState(null);
    const [loading, setLoading] = useState(false);
    const [result, setResult] = useState(null);

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleCompare = async (e) => {
    e.preventDefault();

    try {
      setLoading(true);

      const response = await api.post(
        "/api/proposal/compare",
        formData
      );

      setResult(response.data);

    } catch (err) {
      console.error(err);

      alert(
        err.response?.data?.detail ||
        "Something went wrong."
      );
    } finally {
      setLoading(false);
    }
  };
  const copyProposal = async (text, index) => {
  try {
    await navigator.clipboard.writeText(text);
    setCopiedIndex(index);

    setTimeout(() => {
      setCopiedIndex(null);
    }, 2000);
  } catch (err) {
    console.error(err);
  }
};

 return (
  <div className="min-h-screen bg-slate-100 py-10">
    <div className="max-w-7xl mx-auto px-6">

      {/* Header */}
      <div className="mb-8">
        <h1 className="text-4xl font-bold text-slate-800">
          AI Proposal Comparison
        </h1>

        <p className="text-slate-500 mt-2">
          Compare proposals generated by multiple AI models and automatically
          choose the highest-quality result.
        </p>
      </div>

      <div className="grid lg:grid-cols-3 gap-8">

        {/* Left Side */}
        <div className="lg:col-span-1">

          <div className="bg-white rounded-2xl shadow-md p-6">

            <h2 className="text-xl font-semibold mb-5">
              Generate Proposal
            </h2>

            <form
              onSubmit={handleCompare}
              className="space-y-5"
            >

              <div>
                <label className="block text-sm font-medium mb-2">
                  Job Post
                </label>

                <textarea
                  rows={8}
                  name="job_post"
                  value={formData.job_post}
                  onChange={handleChange}
                  placeholder="Paste the client's job post..."
                  className="w-full rounded-lg border border-gray-300 p-3 focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">
                  Skill
                </label>

                <input
                  type="text"
                  name="skill"
                  value={formData.skill}
                  onChange={handleChange}
                  placeholder="React Developer"
                  className="w-full rounded-lg border border-gray-300 p-3 focus:ring-2 focus:ring-blue-500 outline-none"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-2">
                  Tone
                </label>

                <select
                  name="tone"
                  value={formData.tone}
                  onChange={handleChange}
                  className="w-full rounded-lg border border-gray-300 p-3"
                >
                  <option value="professional">
                    Professional
                  </option>

                  <option value="friendly">
                    Friendly
                  </option>

                  <option value="confident">
                    Confident
                  </option>
                </select>
              </div>

              <button
                disabled={loading}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white rounded-lg py-3 font-semibold transition"
              >
                {loading
                  ? "Generating..."
                  : "Compare Proposals"}
              </button>

            </form>

          </div>

        </div>

        {/* Right Side */}

        <div className="lg:col-span-2">

          {!result?.data ? (

            <div className="bg-white rounded-2xl shadow-md h-full flex items-center justify-center p-10">

              <div className="text-center">

                <div className="text-6xl mb-4">
                  🤖
                </div>

                <h2 className="text-2xl font-bold text-slate-700">
                  No Proposal Yet
                </h2>

                <p className="text-slate-500 mt-3">
                  Submit a job post and Gigora will compare
                  multiple AI models automatically.
                </p>

              </div>

            </div>

          ) : (

            <div className="space-y-6">

              {/* Best Proposal Card */}

              <div className="bg-white rounded-2xl shadow-md p-6">

                <div className="flex justify-between items-center mb-5">

                  <div>

                    <h2 className="text-2xl font-bold">

                      🏆 Best Proposal

                    </h2>

                    <p className="text-gray-500">

                      Generated by

                      <span className="font-semibold text-blue-600 ml-2">

                        {result.data.best_model}

                      </span>

                    </p>

                  </div>

                  <span className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">

                    {result.data.best_score}/100

                  </span>

                </div>

                <div className="whitespace-pre-wrap leading-8 text-gray-700 border rounded-xl p-5 bg-gray-50">

                  {result.data.best_proposal}

                </div>

              </div>

            {/* Comparison Table */}

            <div className="bg-white rounded-2xl shadow-md p-6">

  <h2 className="text-2xl font-bold mb-5">
    AI Model Comparison
  </h2>

  <div className="overflow-x-auto">

    <table className="w-full">

      <thead>

        <tr className="border-b">

          <th className="text-left py-3">
            Model
          </th>

          <th className="text-center py-3">
            Score
          </th>

          <th className="text-center py-3">
            Speed
          </th>

          <th className="text-center py-3">
            Status
          </th>

        </tr>

      </thead>

      <tbody>

        {result.data.all_results.map((item, index) => {

          const winner =
            item.model === result.data.best_model;

          return (

            <tr
              key={index}
              className={`border-b transition
              ${
                winner
                  ? "bg-green-50"
                  : "hover:bg-gray-50"
              }`}
            >

              <td className="py-4 font-medium">

                {winner && "🏆 "}

                {item.model}

              </td>

              <td className="text-center">

                <span
                  className={`px-3 py-1 rounded-full text-sm font-semibold
                  ${
                    winner
                      ? "bg-green-600 text-white"
                      : "bg-blue-100 text-blue-700"
                  }`}
                >

                  {item.score}/100

                </span>

              </td>

              <td className="text-center">

                {item.speed_ms} ms

              </td>

              <td className="text-center">

                {winner ? (

                  <span className="text-green-600 font-semibold">

                    Winner

                  </span>

                ) : (

                  <span className="text-gray-500">

                    Compared

                  </span>

                )}

              </td>

            </tr>

          );

        })}

      </tbody>

    </table>

  </div>

        </div>

{/* All AI Proposals */}

<div className="bg-white rounded-2xl shadow-md p-6">

  <button
    onClick={() => setShowAll(!showAll)}
    className="w-full flex justify-between items-center"
  >

    <h2 className="text-2xl font-bold">

      All AI Proposals

    </h2>

    {showAll ? (
      <ChevronUp />
    ) : (
      <ChevronDown />
    )}

  </button>

  {showAll && (

    <div className="space-y-6 mt-6">

      {result.data.all_results.map((proposal, index) => (

        <div
          key={index}
          className={`rounded-xl border p-6 transition
          ${
            proposal.model === result.data.best_model
              ? "border-green-500 bg-green-50"
              : "border-gray-200"
          }`}
        >

          <div className="flex justify-between items-center mb-4">

            <div>

              <h3 className="text-lg font-bold">

                {proposal.model}

              </h3>

              <p className="text-sm text-gray-500">

                Score: {proposal.score}/100

              </p>

            </div>

            <button
              onClick={() =>
                copyProposal(
                  proposal.text,
                  index
                )
              }
              className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white px-4 py-2 rounded-lg transition"
            >

              {copiedIndex === index ? (

                <>
                  <Check size={18} />
                  Copied
                </>

              ) : (

                <>
                  <Copy size={18} />
                  Copy
                </>

              )}

            </button>

          </div>

          <div className="bg-gray-50 rounded-lg border p-5 whitespace-pre-wrap leading-7 text-gray-700">

            {proposal.text}

          </div>

        </div>

      ))}

    </div>

  )}

</div>


            </div>

          )}

        </div>

      </div>

    </div>
  </div>
);
}

export default ProposalCompare;